name: C/C++ CI

on: [push, pull_request]

jobs:
  build-in-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run make inside Docker container
        run: docker run --rm myapp make

      - name: Run make clean inside Docker container
        run: docker run --rm myapp make clean

